/*
 * Cluster API reference
 *
 * Service name  
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package psm_dss

import (
	"encoding/json"
)

// ClusterDistributedServiceEntityStatus struct for ClusterDistributedServiceEntityStatus
type ClusterDistributedServiceEntityStatus struct {
	DSCSku *string `json:"DSCSku,omitempty"`
	DSCVersion *string `json:"DSCVersion,omitempty"`
	AdmPhaseReason *string `json:"adm-phase-reason,omitempty"`
	AdmissionPhase *string `json:"admission-phase,omitempty"`
	AlomPresent *bool `json:"alom-present,omitempty"`
	Conditions *[]ClusterDSCCondition `json:"conditions,omitempty"`
	ControlPlaneStatus *ClusterDSCControlPlaneStatus `json:"control-plane-status,omitempty"`
	DssInfo *ClusterDSSInfo `json:"dss-info,omitempty"`
	Host *string `json:"host,omitempty"`
	InbandIpConfig *ClusterIPConfig `json:"inband-ip-config,omitempty"`
	Interfaces *[]string `json:"interfaces,omitempty"`
	IpConfig *ClusterIPConfig `json:"ip-config,omitempty"`
	IsConnectedToPsm *bool `json:"is-connected-to-psm,omitempty"`
	// Value should be between 0 and 256.
	NumMacAddress *int64 `json:"num-mac-address,omitempty"`
	PackageType *string `json:"package-type,omitempty"`
	// Should be a valid MAC address.
	PrimaryMac *string `json:"primary-mac,omitempty"`
	SecureBooted *bool `json:"secure-booted,omitempty"`
	SecurityPolicyRuleScaleProfile *string `json:"security-policy-rule-scale-profile,omitempty"`
	SerialNum *string `json:"serial-num,omitempty"`
	SystemInfo *ClusterDSCInfo `json:"system-info,omitempty"`
	UnhealthyServices *[]string `json:"unhealthy-services,omitempty"`
	VersionMismatch *bool `json:"version-mismatch,omitempty"`
}

// NewClusterDistributedServiceEntityStatus instantiates a new ClusterDistributedServiceEntityStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClusterDistributedServiceEntityStatus() *ClusterDistributedServiceEntityStatus {
	this := ClusterDistributedServiceEntityStatus{}
	var admissionPhase string = "unknown"
	this.AdmissionPhase = &admissionPhase
	var numMacAddress int64 = 24
	this.NumMacAddress = &numMacAddress
	var packageType string = "dsc"
	this.PackageType = &packageType
	return &this
}

// NewClusterDistributedServiceEntityStatusWithDefaults instantiates a new ClusterDistributedServiceEntityStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClusterDistributedServiceEntityStatusWithDefaults() *ClusterDistributedServiceEntityStatus {
	this := ClusterDistributedServiceEntityStatus{}
	var admissionPhase string = "unknown"
	this.AdmissionPhase = &admissionPhase
	var numMacAddress int64 = 24
	this.NumMacAddress = &numMacAddress
	var packageType string = "dsc"
	this.PackageType = &packageType
	return &this
}

// GetDSCSku returns the DSCSku field value if set, zero value otherwise.
func (o *ClusterDistributedServiceEntityStatus) GetDSCSku() string {
	if o == nil || o.DSCSku == nil {
		var ret string
		return ret
	}
	return *o.DSCSku
}

// GetDSCSkuOk returns a tuple with the DSCSku field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterDistributedServiceEntityStatus) GetDSCSkuOk() (*string, bool) {
	if o == nil || o.DSCSku == nil {
		return nil, false
	}
	return o.DSCSku, true
}

// HasDSCSku returns a boolean if a field has been set.
func (o *ClusterDistributedServiceEntityStatus) HasDSCSku() bool {
	if o != nil && o.DSCSku != nil {
		return true
	}

	return false
}

// SetDSCSku gets a reference to the given string and assigns it to the DSCSku field.
func (o *ClusterDistributedServiceEntityStatus) SetDSCSku(v string) {
	o.DSCSku = &v
}

// GetDSCVersion returns the DSCVersion field value if set, zero value otherwise.
func (o *ClusterDistributedServiceEntityStatus) GetDSCVersion() string {
	if o == nil || o.DSCVersion == nil {
		var ret string
		return ret
	}
	return *o.DSCVersion
}

// GetDSCVersionOk returns a tuple with the DSCVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterDistributedServiceEntityStatus) GetDSCVersionOk() (*string, bool) {
	if o == nil || o.DSCVersion == nil {
		return nil, false
	}
	return o.DSCVersion, true
}

// HasDSCVersion returns a boolean if a field has been set.
func (o *ClusterDistributedServiceEntityStatus) HasDSCVersion() bool {
	if o != nil && o.DSCVersion != nil {
		return true
	}

	return false
}

// SetDSCVersion gets a reference to the given string and assigns it to the DSCVersion field.
func (o *ClusterDistributedServiceEntityStatus) SetDSCVersion(v string) {
	o.DSCVersion = &v
}

// GetAdmPhaseReason returns the AdmPhaseReason field value if set, zero value otherwise.
func (o *ClusterDistributedServiceEntityStatus) GetAdmPhaseReason() string {
	if o == nil || o.AdmPhaseReason == nil {
		var ret string
		return ret
	}
	return *o.AdmPhaseReason
}

// GetAdmPhaseReasonOk returns a tuple with the AdmPhaseReason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterDistributedServiceEntityStatus) GetAdmPhaseReasonOk() (*string, bool) {
	if o == nil || o.AdmPhaseReason == nil {
		return nil, false
	}
	return o.AdmPhaseReason, true
}

// HasAdmPhaseReason returns a boolean if a field has been set.
func (o *ClusterDistributedServiceEntityStatus) HasAdmPhaseReason() bool {
	if o != nil && o.AdmPhaseReason != nil {
		return true
	}

	return false
}

// SetAdmPhaseReason gets a reference to the given string and assigns it to the AdmPhaseReason field.
func (o *ClusterDistributedServiceEntityStatus) SetAdmPhaseReason(v string) {
	o.AdmPhaseReason = &v
}

// GetAdmissionPhase returns the AdmissionPhase field value if set, zero value otherwise.
func (o *ClusterDistributedServiceEntityStatus) GetAdmissionPhase() string {
	if o == nil || o.AdmissionPhase == nil {
		var ret string
		return ret
	}
	return *o.AdmissionPhase
}

// GetAdmissionPhaseOk returns a tuple with the AdmissionPhase field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterDistributedServiceEntityStatus) GetAdmissionPhaseOk() (*string, bool) {
	if o == nil || o.AdmissionPhase == nil {
		return nil, false
	}
	return o.AdmissionPhase, true
}

// HasAdmissionPhase returns a boolean if a field has been set.
func (o *ClusterDistributedServiceEntityStatus) HasAdmissionPhase() bool {
	if o != nil && o.AdmissionPhase != nil {
		return true
	}

	return false
}

// SetAdmissionPhase gets a reference to the given string and assigns it to the AdmissionPhase field.
func (o *ClusterDistributedServiceEntityStatus) SetAdmissionPhase(v string) {
	o.AdmissionPhase = &v
}

// GetAlomPresent returns the AlomPresent field value if set, zero value otherwise.
func (o *ClusterDistributedServiceEntityStatus) GetAlomPresent() bool {
	if o == nil || o.AlomPresent == nil {
		var ret bool
		return ret
	}
	return *o.AlomPresent
}

// GetAlomPresentOk returns a tuple with the AlomPresent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterDistributedServiceEntityStatus) GetAlomPresentOk() (*bool, bool) {
	if o == nil || o.AlomPresent == nil {
		return nil, false
	}
	return o.AlomPresent, true
}

// HasAlomPresent returns a boolean if a field has been set.
func (o *ClusterDistributedServiceEntityStatus) HasAlomPresent() bool {
	if o != nil && o.AlomPresent != nil {
		return true
	}

	return false
}

// SetAlomPresent gets a reference to the given bool and assigns it to the AlomPresent field.
func (o *ClusterDistributedServiceEntityStatus) SetAlomPresent(v bool) {
	o.AlomPresent = &v
}

// GetConditions returns the Conditions field value if set, zero value otherwise.
func (o *ClusterDistributedServiceEntityStatus) GetConditions() []ClusterDSCCondition {
	if o == nil || o.Conditions == nil {
		var ret []ClusterDSCCondition
		return ret
	}
	return *o.Conditions
}

// GetConditionsOk returns a tuple with the Conditions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterDistributedServiceEntityStatus) GetConditionsOk() (*[]ClusterDSCCondition, bool) {
	if o == nil || o.Conditions == nil {
		return nil, false
	}
	return o.Conditions, true
}

// HasConditions returns a boolean if a field has been set.
func (o *ClusterDistributedServiceEntityStatus) HasConditions() bool {
	if o != nil && o.Conditions != nil {
		return true
	}

	return false
}

// SetConditions gets a reference to the given []ClusterDSCCondition and assigns it to the Conditions field.
func (o *ClusterDistributedServiceEntityStatus) SetConditions(v []ClusterDSCCondition) {
	o.Conditions = &v
}

// GetControlPlaneStatus returns the ControlPlaneStatus field value if set, zero value otherwise.
func (o *ClusterDistributedServiceEntityStatus) GetControlPlaneStatus() ClusterDSCControlPlaneStatus {
	if o == nil || o.ControlPlaneStatus == nil {
		var ret ClusterDSCControlPlaneStatus
		return ret
	}
	return *o.ControlPlaneStatus
}

// GetControlPlaneStatusOk returns a tuple with the ControlPlaneStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterDistributedServiceEntityStatus) GetControlPlaneStatusOk() (*ClusterDSCControlPlaneStatus, bool) {
	if o == nil || o.ControlPlaneStatus == nil {
		return nil, false
	}
	return o.ControlPlaneStatus, true
}

// HasControlPlaneStatus returns a boolean if a field has been set.
func (o *ClusterDistributedServiceEntityStatus) HasControlPlaneStatus() bool {
	if o != nil && o.ControlPlaneStatus != nil {
		return true
	}

	return false
}

// SetControlPlaneStatus gets a reference to the given ClusterDSCControlPlaneStatus and assigns it to the ControlPlaneStatus field.
func (o *ClusterDistributedServiceEntityStatus) SetControlPlaneStatus(v ClusterDSCControlPlaneStatus) {
	o.ControlPlaneStatus = &v
}

// GetDssInfo returns the DssInfo field value if set, zero value otherwise.
func (o *ClusterDistributedServiceEntityStatus) GetDssInfo() ClusterDSSInfo {
	if o == nil || o.DssInfo == nil {
		var ret ClusterDSSInfo
		return ret
	}
	return *o.DssInfo
}

// GetDssInfoOk returns a tuple with the DssInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterDistributedServiceEntityStatus) GetDssInfoOk() (*ClusterDSSInfo, bool) {
	if o == nil || o.DssInfo == nil {
		return nil, false
	}
	return o.DssInfo, true
}

// HasDssInfo returns a boolean if a field has been set.
func (o *ClusterDistributedServiceEntityStatus) HasDssInfo() bool {
	if o != nil && o.DssInfo != nil {
		return true
	}

	return false
}

// SetDssInfo gets a reference to the given ClusterDSSInfo and assigns it to the DssInfo field.
func (o *ClusterDistributedServiceEntityStatus) SetDssInfo(v ClusterDSSInfo) {
	o.DssInfo = &v
}

// GetHost returns the Host field value if set, zero value otherwise.
func (o *ClusterDistributedServiceEntityStatus) GetHost() string {
	if o == nil || o.Host == nil {
		var ret string
		return ret
	}
	return *o.Host
}

// GetHostOk returns a tuple with the Host field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterDistributedServiceEntityStatus) GetHostOk() (*string, bool) {
	if o == nil || o.Host == nil {
		return nil, false
	}
	return o.Host, true
}

// HasHost returns a boolean if a field has been set.
func (o *ClusterDistributedServiceEntityStatus) HasHost() bool {
	if o != nil && o.Host != nil {
		return true
	}

	return false
}

// SetHost gets a reference to the given string and assigns it to the Host field.
func (o *ClusterDistributedServiceEntityStatus) SetHost(v string) {
	o.Host = &v
}

// GetInbandIpConfig returns the InbandIpConfig field value if set, zero value otherwise.
func (o *ClusterDistributedServiceEntityStatus) GetInbandIpConfig() ClusterIPConfig {
	if o == nil || o.InbandIpConfig == nil {
		var ret ClusterIPConfig
		return ret
	}
	return *o.InbandIpConfig
}

// GetInbandIpConfigOk returns a tuple with the InbandIpConfig field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterDistributedServiceEntityStatus) GetInbandIpConfigOk() (*ClusterIPConfig, bool) {
	if o == nil || o.InbandIpConfig == nil {
		return nil, false
	}
	return o.InbandIpConfig, true
}

// HasInbandIpConfig returns a boolean if a field has been set.
func (o *ClusterDistributedServiceEntityStatus) HasInbandIpConfig() bool {
	if o != nil && o.InbandIpConfig != nil {
		return true
	}

	return false
}

// SetInbandIpConfig gets a reference to the given ClusterIPConfig and assigns it to the InbandIpConfig field.
func (o *ClusterDistributedServiceEntityStatus) SetInbandIpConfig(v ClusterIPConfig) {
	o.InbandIpConfig = &v
}

// GetInterfaces returns the Interfaces field value if set, zero value otherwise.
func (o *ClusterDistributedServiceEntityStatus) GetInterfaces() []string {
	if o == nil || o.Interfaces == nil {
		var ret []string
		return ret
	}
	return *o.Interfaces
}

// GetInterfacesOk returns a tuple with the Interfaces field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterDistributedServiceEntityStatus) GetInterfacesOk() (*[]string, bool) {
	if o == nil || o.Interfaces == nil {
		return nil, false
	}
	return o.Interfaces, true
}

// HasInterfaces returns a boolean if a field has been set.
func (o *ClusterDistributedServiceEntityStatus) HasInterfaces() bool {
	if o != nil && o.Interfaces != nil {
		return true
	}

	return false
}

// SetInterfaces gets a reference to the given []string and assigns it to the Interfaces field.
func (o *ClusterDistributedServiceEntityStatus) SetInterfaces(v []string) {
	o.Interfaces = &v
}

// GetIpConfig returns the IpConfig field value if set, zero value otherwise.
func (o *ClusterDistributedServiceEntityStatus) GetIpConfig() ClusterIPConfig {
	if o == nil || o.IpConfig == nil {
		var ret ClusterIPConfig
		return ret
	}
	return *o.IpConfig
}

// GetIpConfigOk returns a tuple with the IpConfig field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterDistributedServiceEntityStatus) GetIpConfigOk() (*ClusterIPConfig, bool) {
	if o == nil || o.IpConfig == nil {
		return nil, false
	}
	return o.IpConfig, true
}

// HasIpConfig returns a boolean if a field has been set.
func (o *ClusterDistributedServiceEntityStatus) HasIpConfig() bool {
	if o != nil && o.IpConfig != nil {
		return true
	}

	return false
}

// SetIpConfig gets a reference to the given ClusterIPConfig and assigns it to the IpConfig field.
func (o *ClusterDistributedServiceEntityStatus) SetIpConfig(v ClusterIPConfig) {
	o.IpConfig = &v
}

// GetIsConnectedToPsm returns the IsConnectedToPsm field value if set, zero value otherwise.
func (o *ClusterDistributedServiceEntityStatus) GetIsConnectedToPsm() bool {
	if o == nil || o.IsConnectedToPsm == nil {
		var ret bool
		return ret
	}
	return *o.IsConnectedToPsm
}

// GetIsConnectedToPsmOk returns a tuple with the IsConnectedToPsm field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterDistributedServiceEntityStatus) GetIsConnectedToPsmOk() (*bool, bool) {
	if o == nil || o.IsConnectedToPsm == nil {
		return nil, false
	}
	return o.IsConnectedToPsm, true
}

// HasIsConnectedToPsm returns a boolean if a field has been set.
func (o *ClusterDistributedServiceEntityStatus) HasIsConnectedToPsm() bool {
	if o != nil && o.IsConnectedToPsm != nil {
		return true
	}

	return false
}

// SetIsConnectedToPsm gets a reference to the given bool and assigns it to the IsConnectedToPsm field.
func (o *ClusterDistributedServiceEntityStatus) SetIsConnectedToPsm(v bool) {
	o.IsConnectedToPsm = &v
}

// GetNumMacAddress returns the NumMacAddress field value if set, zero value otherwise.
func (o *ClusterDistributedServiceEntityStatus) GetNumMacAddress() int64 {
	if o == nil || o.NumMacAddress == nil {
		var ret int64
		return ret
	}
	return *o.NumMacAddress
}

// GetNumMacAddressOk returns a tuple with the NumMacAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterDistributedServiceEntityStatus) GetNumMacAddressOk() (*int64, bool) {
	if o == nil || o.NumMacAddress == nil {
		return nil, false
	}
	return o.NumMacAddress, true
}

// HasNumMacAddress returns a boolean if a field has been set.
func (o *ClusterDistributedServiceEntityStatus) HasNumMacAddress() bool {
	if o != nil && o.NumMacAddress != nil {
		return true
	}

	return false
}

// SetNumMacAddress gets a reference to the given int64 and assigns it to the NumMacAddress field.
func (o *ClusterDistributedServiceEntityStatus) SetNumMacAddress(v int64) {
	o.NumMacAddress = &v
}

// GetPackageType returns the PackageType field value if set, zero value otherwise.
func (o *ClusterDistributedServiceEntityStatus) GetPackageType() string {
	if o == nil || o.PackageType == nil {
		var ret string
		return ret
	}
	return *o.PackageType
}

// GetPackageTypeOk returns a tuple with the PackageType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterDistributedServiceEntityStatus) GetPackageTypeOk() (*string, bool) {
	if o == nil || o.PackageType == nil {
		return nil, false
	}
	return o.PackageType, true
}

// HasPackageType returns a boolean if a field has been set.
func (o *ClusterDistributedServiceEntityStatus) HasPackageType() bool {
	if o != nil && o.PackageType != nil {
		return true
	}

	return false
}

// SetPackageType gets a reference to the given string and assigns it to the PackageType field.
func (o *ClusterDistributedServiceEntityStatus) SetPackageType(v string) {
	o.PackageType = &v
}

// GetPrimaryMac returns the PrimaryMac field value if set, zero value otherwise.
func (o *ClusterDistributedServiceEntityStatus) GetPrimaryMac() string {
	if o == nil || o.PrimaryMac == nil {
		var ret string
		return ret
	}
	return *o.PrimaryMac
}

// GetPrimaryMacOk returns a tuple with the PrimaryMac field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterDistributedServiceEntityStatus) GetPrimaryMacOk() (*string, bool) {
	if o == nil || o.PrimaryMac == nil {
		return nil, false
	}
	return o.PrimaryMac, true
}

// HasPrimaryMac returns a boolean if a field has been set.
func (o *ClusterDistributedServiceEntityStatus) HasPrimaryMac() bool {
	if o != nil && o.PrimaryMac != nil {
		return true
	}

	return false
}

// SetPrimaryMac gets a reference to the given string and assigns it to the PrimaryMac field.
func (o *ClusterDistributedServiceEntityStatus) SetPrimaryMac(v string) {
	o.PrimaryMac = &v
}

// GetSecureBooted returns the SecureBooted field value if set, zero value otherwise.
func (o *ClusterDistributedServiceEntityStatus) GetSecureBooted() bool {
	if o == nil || o.SecureBooted == nil {
		var ret bool
		return ret
	}
	return *o.SecureBooted
}

// GetSecureBootedOk returns a tuple with the SecureBooted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterDistributedServiceEntityStatus) GetSecureBootedOk() (*bool, bool) {
	if o == nil || o.SecureBooted == nil {
		return nil, false
	}
	return o.SecureBooted, true
}

// HasSecureBooted returns a boolean if a field has been set.
func (o *ClusterDistributedServiceEntityStatus) HasSecureBooted() bool {
	if o != nil && o.SecureBooted != nil {
		return true
	}

	return false
}

// SetSecureBooted gets a reference to the given bool and assigns it to the SecureBooted field.
func (o *ClusterDistributedServiceEntityStatus) SetSecureBooted(v bool) {
	o.SecureBooted = &v
}

// GetSecurityPolicyRuleScaleProfile returns the SecurityPolicyRuleScaleProfile field value if set, zero value otherwise.
func (o *ClusterDistributedServiceEntityStatus) GetSecurityPolicyRuleScaleProfile() string {
	if o == nil || o.SecurityPolicyRuleScaleProfile == nil {
		var ret string
		return ret
	}
	return *o.SecurityPolicyRuleScaleProfile
}

// GetSecurityPolicyRuleScaleProfileOk returns a tuple with the SecurityPolicyRuleScaleProfile field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterDistributedServiceEntityStatus) GetSecurityPolicyRuleScaleProfileOk() (*string, bool) {
	if o == nil || o.SecurityPolicyRuleScaleProfile == nil {
		return nil, false
	}
	return o.SecurityPolicyRuleScaleProfile, true
}

// HasSecurityPolicyRuleScaleProfile returns a boolean if a field has been set.
func (o *ClusterDistributedServiceEntityStatus) HasSecurityPolicyRuleScaleProfile() bool {
	if o != nil && o.SecurityPolicyRuleScaleProfile != nil {
		return true
	}

	return false
}

// SetSecurityPolicyRuleScaleProfile gets a reference to the given string and assigns it to the SecurityPolicyRuleScaleProfile field.
func (o *ClusterDistributedServiceEntityStatus) SetSecurityPolicyRuleScaleProfile(v string) {
	o.SecurityPolicyRuleScaleProfile = &v
}

// GetSerialNum returns the SerialNum field value if set, zero value otherwise.
func (o *ClusterDistributedServiceEntityStatus) GetSerialNum() string {
	if o == nil || o.SerialNum == nil {
		var ret string
		return ret
	}
	return *o.SerialNum
}

// GetSerialNumOk returns a tuple with the SerialNum field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterDistributedServiceEntityStatus) GetSerialNumOk() (*string, bool) {
	if o == nil || o.SerialNum == nil {
		return nil, false
	}
	return o.SerialNum, true
}

// HasSerialNum returns a boolean if a field has been set.
func (o *ClusterDistributedServiceEntityStatus) HasSerialNum() bool {
	if o != nil && o.SerialNum != nil {
		return true
	}

	return false
}

// SetSerialNum gets a reference to the given string and assigns it to the SerialNum field.
func (o *ClusterDistributedServiceEntityStatus) SetSerialNum(v string) {
	o.SerialNum = &v
}

// GetSystemInfo returns the SystemInfo field value if set, zero value otherwise.
func (o *ClusterDistributedServiceEntityStatus) GetSystemInfo() ClusterDSCInfo {
	if o == nil || o.SystemInfo == nil {
		var ret ClusterDSCInfo
		return ret
	}
	return *o.SystemInfo
}

// GetSystemInfoOk returns a tuple with the SystemInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterDistributedServiceEntityStatus) GetSystemInfoOk() (*ClusterDSCInfo, bool) {
	if o == nil || o.SystemInfo == nil {
		return nil, false
	}
	return o.SystemInfo, true
}

// HasSystemInfo returns a boolean if a field has been set.
func (o *ClusterDistributedServiceEntityStatus) HasSystemInfo() bool {
	if o != nil && o.SystemInfo != nil {
		return true
	}

	return false
}

// SetSystemInfo gets a reference to the given ClusterDSCInfo and assigns it to the SystemInfo field.
func (o *ClusterDistributedServiceEntityStatus) SetSystemInfo(v ClusterDSCInfo) {
	o.SystemInfo = &v
}

// GetUnhealthyServices returns the UnhealthyServices field value if set, zero value otherwise.
func (o *ClusterDistributedServiceEntityStatus) GetUnhealthyServices() []string {
	if o == nil || o.UnhealthyServices == nil {
		var ret []string
		return ret
	}
	return *o.UnhealthyServices
}

// GetUnhealthyServicesOk returns a tuple with the UnhealthyServices field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterDistributedServiceEntityStatus) GetUnhealthyServicesOk() (*[]string, bool) {
	if o == nil || o.UnhealthyServices == nil {
		return nil, false
	}
	return o.UnhealthyServices, true
}

// HasUnhealthyServices returns a boolean if a field has been set.
func (o *ClusterDistributedServiceEntityStatus) HasUnhealthyServices() bool {
	if o != nil && o.UnhealthyServices != nil {
		return true
	}

	return false
}

// SetUnhealthyServices gets a reference to the given []string and assigns it to the UnhealthyServices field.
func (o *ClusterDistributedServiceEntityStatus) SetUnhealthyServices(v []string) {
	o.UnhealthyServices = &v
}

// GetVersionMismatch returns the VersionMismatch field value if set, zero value otherwise.
func (o *ClusterDistributedServiceEntityStatus) GetVersionMismatch() bool {
	if o == nil || o.VersionMismatch == nil {
		var ret bool
		return ret
	}
	return *o.VersionMismatch
}

// GetVersionMismatchOk returns a tuple with the VersionMismatch field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterDistributedServiceEntityStatus) GetVersionMismatchOk() (*bool, bool) {
	if o == nil || o.VersionMismatch == nil {
		return nil, false
	}
	return o.VersionMismatch, true
}

// HasVersionMismatch returns a boolean if a field has been set.
func (o *ClusterDistributedServiceEntityStatus) HasVersionMismatch() bool {
	if o != nil && o.VersionMismatch != nil {
		return true
	}

	return false
}

// SetVersionMismatch gets a reference to the given bool and assigns it to the VersionMismatch field.
func (o *ClusterDistributedServiceEntityStatus) SetVersionMismatch(v bool) {
	o.VersionMismatch = &v
}

func (o ClusterDistributedServiceEntityStatus) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.DSCSku != nil {
		toSerialize["DSCSku"] = o.DSCSku
	}
	if o.DSCVersion != nil {
		toSerialize["DSCVersion"] = o.DSCVersion
	}
	if o.AdmPhaseReason != nil {
		toSerialize["adm-phase-reason"] = o.AdmPhaseReason
	}
	if o.AdmissionPhase != nil {
		toSerialize["admission-phase"] = o.AdmissionPhase
	}
	if o.AlomPresent != nil {
		toSerialize["alom-present"] = o.AlomPresent
	}
	if o.Conditions != nil {
		toSerialize["conditions"] = o.Conditions
	}
	if o.ControlPlaneStatus != nil {
		toSerialize["control-plane-status"] = o.ControlPlaneStatus
	}
	if o.DssInfo != nil {
		toSerialize["dss-info"] = o.DssInfo
	}
	if o.Host != nil {
		toSerialize["host"] = o.Host
	}
	if o.InbandIpConfig != nil {
		toSerialize["inband-ip-config"] = o.InbandIpConfig
	}
	if o.Interfaces != nil {
		toSerialize["interfaces"] = o.Interfaces
	}
	if o.IpConfig != nil {
		toSerialize["ip-config"] = o.IpConfig
	}
	if o.IsConnectedToPsm != nil {
		toSerialize["is-connected-to-psm"] = o.IsConnectedToPsm
	}
	if o.NumMacAddress != nil {
		toSerialize["num-mac-address"] = o.NumMacAddress
	}
	if o.PackageType != nil {
		toSerialize["package-type"] = o.PackageType
	}
	if o.PrimaryMac != nil {
		toSerialize["primary-mac"] = o.PrimaryMac
	}
	if o.SecureBooted != nil {
		toSerialize["secure-booted"] = o.SecureBooted
	}
	if o.SecurityPolicyRuleScaleProfile != nil {
		toSerialize["security-policy-rule-scale-profile"] = o.SecurityPolicyRuleScaleProfile
	}
	if o.SerialNum != nil {
		toSerialize["serial-num"] = o.SerialNum
	}
	if o.SystemInfo != nil {
		toSerialize["system-info"] = o.SystemInfo
	}
	if o.UnhealthyServices != nil {
		toSerialize["unhealthy-services"] = o.UnhealthyServices
	}
	if o.VersionMismatch != nil {
		toSerialize["version-mismatch"] = o.VersionMismatch
	}
	return json.Marshal(toSerialize)
}

type NullableClusterDistributedServiceEntityStatus struct {
	value *ClusterDistributedServiceEntityStatus
	isSet bool
}

func (v NullableClusterDistributedServiceEntityStatus) Get() *ClusterDistributedServiceEntityStatus {
	return v.value
}

func (v *NullableClusterDistributedServiceEntityStatus) Set(val *ClusterDistributedServiceEntityStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableClusterDistributedServiceEntityStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableClusterDistributedServiceEntityStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClusterDistributedServiceEntityStatus(val *ClusterDistributedServiceEntityStatus) *NullableClusterDistributedServiceEntityStatus {
	return &NullableClusterDistributedServiceEntityStatus{value: val, isSet: true}
}

func (v NullableClusterDistributedServiceEntityStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClusterDistributedServiceEntityStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


