/*
 * Cluster API reference
 *
 * Service name  
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package psm_dss

import (
	"encoding/json"
)

// ClusterFlowExportPolicyRef struct for ClusterFlowExportPolicyRef
type ClusterFlowExportPolicyRef struct {
	// Name of FlowExportPolicy.
	Name *string `json:"name,omitempty"`
	// Tenant of FlowExportPolicy.
	Tenant *string `json:"tenant,omitempty"`
}

// NewClusterFlowExportPolicyRef instantiates a new ClusterFlowExportPolicyRef object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClusterFlowExportPolicyRef() *ClusterFlowExportPolicyRef {
	this := ClusterFlowExportPolicyRef{}
	var tenant string = "default"
	this.Tenant = &tenant
	return &this
}

// NewClusterFlowExportPolicyRefWithDefaults instantiates a new ClusterFlowExportPolicyRef object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClusterFlowExportPolicyRefWithDefaults() *ClusterFlowExportPolicyRef {
	this := ClusterFlowExportPolicyRef{}
	var tenant string = "default"
	this.Tenant = &tenant
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ClusterFlowExportPolicyRef) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterFlowExportPolicyRef) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ClusterFlowExportPolicyRef) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ClusterFlowExportPolicyRef) SetName(v string) {
	o.Name = &v
}

// GetTenant returns the Tenant field value if set, zero value otherwise.
func (o *ClusterFlowExportPolicyRef) GetTenant() string {
	if o == nil || o.Tenant == nil {
		var ret string
		return ret
	}
	return *o.Tenant
}

// GetTenantOk returns a tuple with the Tenant field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterFlowExportPolicyRef) GetTenantOk() (*string, bool) {
	if o == nil || o.Tenant == nil {
		return nil, false
	}
	return o.Tenant, true
}

// HasTenant returns a boolean if a field has been set.
func (o *ClusterFlowExportPolicyRef) HasTenant() bool {
	if o != nil && o.Tenant != nil {
		return true
	}

	return false
}

// SetTenant gets a reference to the given string and assigns it to the Tenant field.
func (o *ClusterFlowExportPolicyRef) SetTenant(v string) {
	o.Tenant = &v
}

func (o ClusterFlowExportPolicyRef) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Tenant != nil {
		toSerialize["tenant"] = o.Tenant
	}
	return json.Marshal(toSerialize)
}

type NullableClusterFlowExportPolicyRef struct {
	value *ClusterFlowExportPolicyRef
	isSet bool
}

func (v NullableClusterFlowExportPolicyRef) Get() *ClusterFlowExportPolicyRef {
	return v.value
}

func (v *NullableClusterFlowExportPolicyRef) Set(val *ClusterFlowExportPolicyRef) {
	v.value = val
	v.isSet = true
}

func (v NullableClusterFlowExportPolicyRef) IsSet() bool {
	return v.isSet
}

func (v *NullableClusterFlowExportPolicyRef) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClusterFlowExportPolicyRef(val *ClusterFlowExportPolicyRef) *NullableClusterFlowExportPolicyRef {
	return &NullableClusterFlowExportPolicyRef{value: val, isSet: true}
}

func (v NullableClusterFlowExportPolicyRef) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClusterFlowExportPolicyRef) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


