/*
 * Workload API reference
 *
 * Service name  
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package psm_dss

import (
	"encoding/json"
)

// WorkloadWorkloadGroup WorkloadGroup represents a VM, container/pod or Baremetal using labels or IP.
type WorkloadWorkloadGroup struct {
	ApiVersion *string `json:"api-version,omitempty"`
	Kind *string `json:"kind,omitempty"`
	Meta *ApiObjectMeta `json:"meta,omitempty"`
	Spec *WorkloadWorkloadGroupSpec `json:"spec,omitempty"`
	Status *WorkloadWorkloadGroupStatus `json:"status,omitempty"`
}

// NewWorkloadWorkloadGroup instantiates a new WorkloadWorkloadGroup object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWorkloadWorkloadGroup() *WorkloadWorkloadGroup {
	this := WorkloadWorkloadGroup{}
	return &this
}

// NewWorkloadWorkloadGroupWithDefaults instantiates a new WorkloadWorkloadGroup object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWorkloadWorkloadGroupWithDefaults() *WorkloadWorkloadGroup {
	this := WorkloadWorkloadGroup{}
	return &this
}

// GetApiVersion returns the ApiVersion field value if set, zero value otherwise.
func (o *WorkloadWorkloadGroup) GetApiVersion() string {
	if o == nil || o.ApiVersion == nil {
		var ret string
		return ret
	}
	return *o.ApiVersion
}

// GetApiVersionOk returns a tuple with the ApiVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkloadWorkloadGroup) GetApiVersionOk() (*string, bool) {
	if o == nil || o.ApiVersion == nil {
		return nil, false
	}
	return o.ApiVersion, true
}

// HasApiVersion returns a boolean if a field has been set.
func (o *WorkloadWorkloadGroup) HasApiVersion() bool {
	if o != nil && o.ApiVersion != nil {
		return true
	}

	return false
}

// SetApiVersion gets a reference to the given string and assigns it to the ApiVersion field.
func (o *WorkloadWorkloadGroup) SetApiVersion(v string) {
	o.ApiVersion = &v
}

// GetKind returns the Kind field value if set, zero value otherwise.
func (o *WorkloadWorkloadGroup) GetKind() string {
	if o == nil || o.Kind == nil {
		var ret string
		return ret
	}
	return *o.Kind
}

// GetKindOk returns a tuple with the Kind field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkloadWorkloadGroup) GetKindOk() (*string, bool) {
	if o == nil || o.Kind == nil {
		return nil, false
	}
	return o.Kind, true
}

// HasKind returns a boolean if a field has been set.
func (o *WorkloadWorkloadGroup) HasKind() bool {
	if o != nil && o.Kind != nil {
		return true
	}

	return false
}

// SetKind gets a reference to the given string and assigns it to the Kind field.
func (o *WorkloadWorkloadGroup) SetKind(v string) {
	o.Kind = &v
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *WorkloadWorkloadGroup) GetMeta() ApiObjectMeta {
	if o == nil || o.Meta == nil {
		var ret ApiObjectMeta
		return ret
	}
	return *o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkloadWorkloadGroup) GetMetaOk() (*ApiObjectMeta, bool) {
	if o == nil || o.Meta == nil {
		return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *WorkloadWorkloadGroup) HasMeta() bool {
	if o != nil && o.Meta != nil {
		return true
	}

	return false
}

// SetMeta gets a reference to the given ApiObjectMeta and assigns it to the Meta field.
func (o *WorkloadWorkloadGroup) SetMeta(v ApiObjectMeta) {
	o.Meta = &v
}

// GetSpec returns the Spec field value if set, zero value otherwise.
func (o *WorkloadWorkloadGroup) GetSpec() WorkloadWorkloadGroupSpec {
	if o == nil || o.Spec == nil {
		var ret WorkloadWorkloadGroupSpec
		return ret
	}
	return *o.Spec
}

// GetSpecOk returns a tuple with the Spec field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkloadWorkloadGroup) GetSpecOk() (*WorkloadWorkloadGroupSpec, bool) {
	if o == nil || o.Spec == nil {
		return nil, false
	}
	return o.Spec, true
}

// HasSpec returns a boolean if a field has been set.
func (o *WorkloadWorkloadGroup) HasSpec() bool {
	if o != nil && o.Spec != nil {
		return true
	}

	return false
}

// SetSpec gets a reference to the given WorkloadWorkloadGroupSpec and assigns it to the Spec field.
func (o *WorkloadWorkloadGroup) SetSpec(v WorkloadWorkloadGroupSpec) {
	o.Spec = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *WorkloadWorkloadGroup) GetStatus() WorkloadWorkloadGroupStatus {
	if o == nil || o.Status == nil {
		var ret WorkloadWorkloadGroupStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkloadWorkloadGroup) GetStatusOk() (*WorkloadWorkloadGroupStatus, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *WorkloadWorkloadGroup) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given WorkloadWorkloadGroupStatus and assigns it to the Status field.
func (o *WorkloadWorkloadGroup) SetStatus(v WorkloadWorkloadGroupStatus) {
	o.Status = &v
}

func (o WorkloadWorkloadGroup) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.ApiVersion != nil {
		toSerialize["api-version"] = o.ApiVersion
	}
	if o.Kind != nil {
		toSerialize["kind"] = o.Kind
	}
	if o.Meta != nil {
		toSerialize["meta"] = o.Meta
	}
	if o.Spec != nil {
		toSerialize["spec"] = o.Spec
	}
	if o.Status != nil {
		toSerialize["status"] = o.Status
	}
	return json.Marshal(toSerialize)
}

type NullableWorkloadWorkloadGroup struct {
	value *WorkloadWorkloadGroup
	isSet bool
}

func (v NullableWorkloadWorkloadGroup) Get() *WorkloadWorkloadGroup {
	return v.value
}

func (v *NullableWorkloadWorkloadGroup) Set(val *WorkloadWorkloadGroup) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkloadWorkloadGroup) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkloadWorkloadGroup) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkloadWorkloadGroup(val *WorkloadWorkloadGroup) *NullableWorkloadWorkloadGroup {
	return &NullableWorkloadWorkloadGroup{value: val, isSet: true}
}

func (v NullableWorkloadWorkloadGroup) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkloadWorkloadGroup) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


