/*
 * Cluster API reference
 *
 * Service name  
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package psm_dss

import (
	"encoding/json"
)

// ClusterDistributedServiceEntity struct for ClusterDistributedServiceEntity
type ClusterDistributedServiceEntity struct {
	ApiVersion *string `json:"api-version,omitempty"`
	Kind *string `json:"kind,omitempty"`
	Meta *ApiObjectMeta `json:"meta,omitempty"`
	Spec *ClusterDistributedServiceEntitySpec `json:"spec,omitempty"`
	Status *ClusterDistributedServiceEntityStatus `json:"status,omitempty"`
}

// NewClusterDistributedServiceEntity instantiates a new ClusterDistributedServiceEntity object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClusterDistributedServiceEntity() *ClusterDistributedServiceEntity {
	this := ClusterDistributedServiceEntity{}
	return &this
}

// NewClusterDistributedServiceEntityWithDefaults instantiates a new ClusterDistributedServiceEntity object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClusterDistributedServiceEntityWithDefaults() *ClusterDistributedServiceEntity {
	this := ClusterDistributedServiceEntity{}
	return &this
}

// GetApiVersion returns the ApiVersion field value if set, zero value otherwise.
func (o *ClusterDistributedServiceEntity) GetApiVersion() string {
	if o == nil || o.ApiVersion == nil {
		var ret string
		return ret
	}
	return *o.ApiVersion
}

// GetApiVersionOk returns a tuple with the ApiVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterDistributedServiceEntity) GetApiVersionOk() (*string, bool) {
	if o == nil || o.ApiVersion == nil {
		return nil, false
	}
	return o.ApiVersion, true
}

// HasApiVersion returns a boolean if a field has been set.
func (o *ClusterDistributedServiceEntity) HasApiVersion() bool {
	if o != nil && o.ApiVersion != nil {
		return true
	}

	return false
}

// SetApiVersion gets a reference to the given string and assigns it to the ApiVersion field.
func (o *ClusterDistributedServiceEntity) SetApiVersion(v string) {
	o.ApiVersion = &v
}

// GetKind returns the Kind field value if set, zero value otherwise.
func (o *ClusterDistributedServiceEntity) GetKind() string {
	if o == nil || o.Kind == nil {
		var ret string
		return ret
	}
	return *o.Kind
}

// GetKindOk returns a tuple with the Kind field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterDistributedServiceEntity) GetKindOk() (*string, bool) {
	if o == nil || o.Kind == nil {
		return nil, false
	}
	return o.Kind, true
}

// HasKind returns a boolean if a field has been set.
func (o *ClusterDistributedServiceEntity) HasKind() bool {
	if o != nil && o.Kind != nil {
		return true
	}

	return false
}

// SetKind gets a reference to the given string and assigns it to the Kind field.
func (o *ClusterDistributedServiceEntity) SetKind(v string) {
	o.Kind = &v
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *ClusterDistributedServiceEntity) GetMeta() ApiObjectMeta {
	if o == nil || o.Meta == nil {
		var ret ApiObjectMeta
		return ret
	}
	return *o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterDistributedServiceEntity) GetMetaOk() (*ApiObjectMeta, bool) {
	if o == nil || o.Meta == nil {
		return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *ClusterDistributedServiceEntity) HasMeta() bool {
	if o != nil && o.Meta != nil {
		return true
	}

	return false
}

// SetMeta gets a reference to the given ApiObjectMeta and assigns it to the Meta field.
func (o *ClusterDistributedServiceEntity) SetMeta(v ApiObjectMeta) {
	o.Meta = &v
}

// GetSpec returns the Spec field value if set, zero value otherwise.
func (o *ClusterDistributedServiceEntity) GetSpec() ClusterDistributedServiceEntitySpec {
	if o == nil || o.Spec == nil {
		var ret ClusterDistributedServiceEntitySpec
		return ret
	}
	return *o.Spec
}

// GetSpecOk returns a tuple with the Spec field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterDistributedServiceEntity) GetSpecOk() (*ClusterDistributedServiceEntitySpec, bool) {
	if o == nil || o.Spec == nil {
		return nil, false
	}
	return o.Spec, true
}

// HasSpec returns a boolean if a field has been set.
func (o *ClusterDistributedServiceEntity) HasSpec() bool {
	if o != nil && o.Spec != nil {
		return true
	}

	return false
}

// SetSpec gets a reference to the given ClusterDistributedServiceEntitySpec and assigns it to the Spec field.
func (o *ClusterDistributedServiceEntity) SetSpec(v ClusterDistributedServiceEntitySpec) {
	o.Spec = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *ClusterDistributedServiceEntity) GetStatus() ClusterDistributedServiceEntityStatus {
	if o == nil || o.Status == nil {
		var ret ClusterDistributedServiceEntityStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterDistributedServiceEntity) GetStatusOk() (*ClusterDistributedServiceEntityStatus, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *ClusterDistributedServiceEntity) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given ClusterDistributedServiceEntityStatus and assigns it to the Status field.
func (o *ClusterDistributedServiceEntity) SetStatus(v ClusterDistributedServiceEntityStatus) {
	o.Status = &v
}

func (o ClusterDistributedServiceEntity) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.ApiVersion != nil {
		toSerialize["api-version"] = o.ApiVersion
	}
	if o.Kind != nil {
		toSerialize["kind"] = o.Kind
	}
	if o.Meta != nil {
		toSerialize["meta"] = o.Meta
	}
	if o.Spec != nil {
		toSerialize["spec"] = o.Spec
	}
	if o.Status != nil {
		toSerialize["status"] = o.Status
	}
	return json.Marshal(toSerialize)
}

type NullableClusterDistributedServiceEntity struct {
	value *ClusterDistributedServiceEntity
	isSet bool
}

func (v NullableClusterDistributedServiceEntity) Get() *ClusterDistributedServiceEntity {
	return v.value
}

func (v *NullableClusterDistributedServiceEntity) Set(val *ClusterDistributedServiceEntity) {
	v.value = val
	v.isSet = true
}

func (v NullableClusterDistributedServiceEntity) IsSet() bool {
	return v.isSet
}

func (v *NullableClusterDistributedServiceEntity) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClusterDistributedServiceEntity(val *ClusterDistributedServiceEntity) *NullableClusterDistributedServiceEntity {
	return &NullableClusterDistributedServiceEntity{value: val, isSet: true}
}

func (v NullableClusterDistributedServiceEntity) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClusterDistributedServiceEntity) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


