/*
 * Workload API reference
 *
 * Service name  
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package psm_dss

import (
	"encoding/json"
)

// WorkloadInterfaceMigrationStatus struct for WorkloadInterfaceMigrationStatus
type WorkloadInterfaceMigrationStatus struct {
	Reason *string `json:"reason,omitempty"`
	// The status from the dataplane performing migration.
	Status *string `json:"status,omitempty"`
}

// NewWorkloadInterfaceMigrationStatus instantiates a new WorkloadInterfaceMigrationStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWorkloadInterfaceMigrationStatus() *WorkloadInterfaceMigrationStatus {
	this := WorkloadInterfaceMigrationStatus{}
	var status string = "none"
	this.Status = &status
	return &this
}

// NewWorkloadInterfaceMigrationStatusWithDefaults instantiates a new WorkloadInterfaceMigrationStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWorkloadInterfaceMigrationStatusWithDefaults() *WorkloadInterfaceMigrationStatus {
	this := WorkloadInterfaceMigrationStatus{}
	var status string = "none"
	this.Status = &status
	return &this
}

// GetReason returns the Reason field value if set, zero value otherwise.
func (o *WorkloadInterfaceMigrationStatus) GetReason() string {
	if o == nil || o.Reason == nil {
		var ret string
		return ret
	}
	return *o.Reason
}

// GetReasonOk returns a tuple with the Reason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkloadInterfaceMigrationStatus) GetReasonOk() (*string, bool) {
	if o == nil || o.Reason == nil {
		return nil, false
	}
	return o.Reason, true
}

// HasReason returns a boolean if a field has been set.
func (o *WorkloadInterfaceMigrationStatus) HasReason() bool {
	if o != nil && o.Reason != nil {
		return true
	}

	return false
}

// SetReason gets a reference to the given string and assigns it to the Reason field.
func (o *WorkloadInterfaceMigrationStatus) SetReason(v string) {
	o.Reason = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *WorkloadInterfaceMigrationStatus) GetStatus() string {
	if o == nil || o.Status == nil {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkloadInterfaceMigrationStatus) GetStatusOk() (*string, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *WorkloadInterfaceMigrationStatus) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *WorkloadInterfaceMigrationStatus) SetStatus(v string) {
	o.Status = &v
}

func (o WorkloadInterfaceMigrationStatus) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Reason != nil {
		toSerialize["reason"] = o.Reason
	}
	if o.Status != nil {
		toSerialize["status"] = o.Status
	}
	return json.Marshal(toSerialize)
}

type NullableWorkloadInterfaceMigrationStatus struct {
	value *WorkloadInterfaceMigrationStatus
	isSet bool
}

func (v NullableWorkloadInterfaceMigrationStatus) Get() *WorkloadInterfaceMigrationStatus {
	return v.value
}

func (v *NullableWorkloadInterfaceMigrationStatus) Set(val *WorkloadInterfaceMigrationStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkloadInterfaceMigrationStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkloadInterfaceMigrationStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkloadInterfaceMigrationStatus(val *WorkloadInterfaceMigrationStatus) *NullableWorkloadInterfaceMigrationStatus {
	return &NullableWorkloadInterfaceMigrationStatus{value: val, isSet: true}
}

func (v NullableWorkloadInterfaceMigrationStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkloadInterfaceMigrationStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


